global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['api:3000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113'] 